name: flutter_karaoke_player
description: Karaoke Player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  dio: ^5.3.3
  dio_http2_adapter: ^2.0.0
  pretty_dio_logger: ^1.1.1
  archive: ^3.3.0
  image: ^4.1.3
  bitmap: ^0.1.2
  fluent_ui: ^4.7.7
  provider: ^6.0.3
  path_provider: ^2.0.11
  bitsdojo_window: ^0.1.2
  media_kit: ^1.1.10+1
  get_it: ^7.2.0
  web_socket_channel: ^2.2.0
  qr_flutter: ^4.0.0

  karaoke_request_api:
    hosted: https://dart.pkg.jetbrains.space/flup/p/main/flup/
    version: ^1.8.4
  media_kit_video: ^1.0.2
  media_kit_libs_video: ^1.0.4
  media_kit_libs_audio: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  msix: ^3.6.3
dependency_overrides:
  intl: 0.18.1
flutter:
  uses-material-design: true

msix_config:
  display_name: Karaoke Player
  publisher_display_name: Felipe Uematsu
  identity_name: dev.felipeuematsu.karaoke_player
  msix_version: 1.0.0.0
#  logo_path: C:\path\to\logo.png
  capabilities: internetClient