name: flutter_karaoke_player
description: Karaoke Player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  dio: ^4.0.4
  dio_http2_adapter: ^2.0.0
  pretty_dio_logger: ^1.1.1
  archive: ^3.3.0
  image: ^3.2.0
  bitmap: ^0.1.2
  fluent_ui: ^3.12.0
  provider: ^6.0.3
  path_provider: ^2.0.11
  bitsdojo_window: ^0.1.2
  dart_vlc: ^0.3.0
  get_it: ^7.2.0
  web_socket_channel: ^2.2.0
  qr_flutter: ^4.0.0

  karaoke_request_api:
    git:
      url: https://github.com/felipeuematsu/karaoke_request_api
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.6.3
flutter:
  uses-material-design: true

msix_config:
  display_name: Karaoke Player
  publisher_display_name: Felipe Uematsu
  identity_name: dev.felipeuematsu.karaoke_player
  msix_version: 1.0.0.0
#  logo_path: C:\path\to\logo.png
  capabilities: internetClient